{% set version = "0.9.1" %}

package:
  name: glueviz
  version: {{version}}

source:
  fn: glueviz-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-{{version}}.tar.gz
  md5: 365887017580e243fb008d8109f2bc16

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  osx_is_app: True

requirements:

  build:
    - python
    - setuptools

  run:

    # The following is needed to make sure that the package works as a GUI
    # application (glue needs to be run with python.app, not python)
    - python.app  # [osx]

    # Required dependencies
    - python
    - numpy >=1.9
    - pandas >=0.14
    - astropy >=1
    - matplotlib >=1.4
    - qt 4.8.*
    - setuptools >=1.0
    - pyqt 4.11.*

    # Optional dependencies (defined in ``extras_require``)
    - dill
    - h5py
    - scipy
    - scikit-image
    - ipython >=1
    - ipykernel
    - qt 4.8.*
    - plotly
    - xlrd
    - glue-vispy-viewers >=0.5

test:
  imports:
    - glue
    - glue.core
    - glue.app.qt
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
