# NOTE: this is a meta-package that includes the core glue-core code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# 'app:' entry here and not in the glue-core package. Even though glueviz is a
# Python package on PyPI, and has a setup.py file, we don't include a build command
# below since the only purpose of that command is to trigger the installation of the
# dependencies.

{% set version = "1.1.0" %}

package:
  name: glueviz
  version: {{ version }}

source:
  fn: glueviz-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-{{ version }}.tar.gz
  sha256: e9d52ce7b18249c8885a07ec1e6615c619d80a4a2887852720ee2bc5a0f8262e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=30.3
    - setuptools_scm
  run:
    - python
    - glue-core >=1.0.0
    - glue-vispy-viewers >=1.0.0

test:
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
