# NOTE: this is a meta-package that includes the core glue-core code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# 'app:' entry here and not in the glue-core package. Even though glueviz is a
# Python package on PyPI, and has a setup.py file, we don't include a build command
# below since the only purpose of that command is to trigger the installation of the
# dependencies.

{% set version = "1.3.0" %}

package:
  name: glueviz
  version: {{ version }}

source:
  fn: glueviz-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-{{ version }}.tar.gz
  sha256: 0b8ccbc4d6c331ea64b80eca66573517ad4fcfb37535fdf2ddd1ef1692f47cee

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools >=30.3
    - setuptools_scm
  run:
    - python
    - glue-core >=1.1.0
    - glue-qt >=0.1.0
    - glue-vispy-viewers >=1.0.3

test:
  commands:
    - glue --version

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog
