# NOTE: this is a meta-package that includes the core glue-core code as well as stable
# plugins. This is the main conda package we want in the Navigator, so we add the
# app: entry here and not in the glue-core package. Even though glueviz is a
# Python package on PyPI, and has a setup.py file, we don't include a build command
# below since the only purpose of that command is to trigger the installation of the
# dependencies.

{% set version = "0.15.1" %}

package:
  name: glueviz
  version: {{version}}

source:
  fn: glueviz-{{version}}.tar.gz
  url: https://pypi.io/packages/source/g/glueviz/glueviz-{{version}}.tar.gz
  sha256: 4b3f9b6f5956ca3de23759ccda51a05ef485fb64d80a19e2f057dcd35040bed2

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - setuptools >=30.3
    - setuptools_scm
  run:
    - glue-core >=0.15.3
    - glue-vispy-viewers >=0.12.2

test:
  commands:
    - glue --version
    - glue-deps list

app:
  entry: glue
  icon: logo.png
  summary: Multi-dimensional linked data exploration
  type: desk

about:
  home: http://glueviz.org
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Multi-dimensional linked data exploration

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
